server:
  port: 8089
  servlet:
    context-path: /jwtauth
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwtauth?serverTimezone=Asia/Seoul
    username: root
    password: Apassword!1
  output:
    ansi:
      enable: NAVER
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret-key: retunbliss-key
  access-token-expire-length: 3600000
  refresh-token-expire-length: 604800000
  header-name: "returnbliss-bearer"
